### ISSUE TITLE
:bug: [FIX]: Criar pasta e anexar o arquivo adivinhar.md

### ISSUE THREAD

**Issue by paulovieirajr** [Spring-Rookies/headfirstjava#3]
## URGENTE - REMOÇÃO DE ARQUIVO DO DIRETÓRIO RAIZ

Favor, criar uma pasta com especificação para anexar o arquivo adivinhar.md que está no diretório raiz. Está fora dos padrões.

Att, Junior.

**Comment by Elias-WTS** [comment]
Ok, será providenciado o mais rápido possível.

**Comment by Elias-WTS** [comment]
O diretório raiz foi corrigido, favor verificar o PR.
